WARNING  urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000014886789220>: Failed to resolve 'hub.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x0000014886789DF0>: Failed to resolve 'hub.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPConnection object at 0x00000148867897C0>: Failed to resolve 'hub.browserstack.com' ([Errno 11001] getaddrinfo failed)")': /wd/hub/session